<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN">
<html>
<head>

    <title>MVC Test</title>
    
    <script type="text/javascript" src="/assets/js/global.js"></script>
    
    <?php echo $jsFiles; ?>
    
    <?php echo $cssFiles; ?>
    
</head>
<body>
    <div id="header">
        <p> This is a basic MVC app.  </p>
    </div>

    <div id="content"><?php echo $content; ?></div>
</body>
</html>
